color0         #121212
color1         #3a3a3a
color2         #585858
color3         #626262
color4         #808080
color5         #8a8a8a
color6         #9e9e9e
color7         #bcbcbc
color8         #4e4e4e
color9         #767676
color10        #8e8e8e
color11        #a8a8a8
color12        #b2b2b2
color13        #c6c6c6
color14        #dadada
color15        #ffffff