source = colors.conf

general {
    hide_cursor = true
}

# auth {
#     pam:enabled = true
#     pam:module = "hyprlock"
#     fingerprint:enabled = false
#     fingerprint:ready_message = "(Scan fingerprint to unlock)"
#     fingerprint:present_message = "Scanning fingerprint"
#     fingerprint:retry_delay = 250
# }

background {
    monitor =
    path = $image
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    inner_color = $on_surface
    font_color = $surface
    check_color = $primary
    fail_color = $error
    fade_on_empty = false
    font_family = "JetBrainsMono Nerd Font"
    capslock_color = $tertiary
}

label {
    monitor =
    text = $TIME
    color = $primary
    font_size = 55
    font_family = "Noto Sans"
    position = 0, 80
}