[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/theme/hypr.lua'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/theme/kitty.conf'
post_hook = "pkill -SIGUSR1 kitty"
