# --- Main Colors ---
background            #19120d
foreground            #f0dfd7
cursor                #f0dfd7
cursor_text_color     #19120d

selection_background  #5c4130
selection_foreground  #ffdbc8

url_color             #cbc993

# --- ANSI Colors ---
color0                #19120d
color1                #ffb4ab
color2                #cbc993
color3                #e5bfa9
color4                #ffb689
color5                #cbc993
color6                #e5bfa9
color7                #f0dfd7

color8                #52443c
color9                #93000a
color10               #49491e
color11               #5c4130
color12               #6e380f
color13               #5c4130
color14               #49491e
color15               #d7c3b8

# --- UI Elements ---
active_tab_foreground   #512300
active_tab_background   #ffb689
inactive_tab_foreground #ffdbc8
inactive_tab_background #6e380f

active_border_color     #ffb689
inactive_border_color   #9f8d83

# --- Marks ---
mark1_foreground        #311300
mark1_background        #ffdbc8
mark2_foreground        #2b1709
mark2_background        #ffdbc8
mark3_foreground        #1d1d00
mark3_background        #e7e6ac