# --- Theme ---
include current-theme.conf

# --- Font ---
font_family JetBrainsMono Nerd Font
disable_ligatures never

# --- Cursor ---
cursor_stop_blinking_after 0
cursor_trail 10

# --- Mouse & Link ---
mouse_hide_wait 3.0

# --- Performance & Bell ---
enable_audio_bell no

# --- Window Layout ---
window_padding_width 30
confirm_os_window_close 0

# --- Shell ---
shell zsh
