wireplumber.settings = {
  ["default.audio.sink"] = "alsa_output.usb-Logitech_G_series_G435_Wireless_Gaming_Headset_202105190004-00.analog-stereo",
  ["default.audio.source"] = "alsa_input.usb-Logitech_Yeti_GX_Mono-00.mono-fallback"
}
