[config]

[config.wallpaper]
set = true
command = "awww img {{ image }} --transition-type center"

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors'
output_path = '~/themes/colorful/dunstrc'
post_hook = 'dunstctl reload'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/themes/colorful/hypr.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/themes/colorful/hypr.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/themes/colorful/kitty.conf'
post_hook = "killall -SIGUSR1 kitty 2>/dev/null || true"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/themes/colorful/rofi.rasi'

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/themes/colorful/spotify.ini'
post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/themes/colorful/waybar.css'
post_hook = "pkill -SIGUSR2 waybar"
